### ISSUE TITLE
Функция не должна формировать и выводить сообщение для пользователя

### ISSUE THREAD

**Issue by andrey-ilyin** [miredirex/backend-course#1]
https://github.com/miredirex/backend-course/blob/c8fb5abcb1a73331dbef3007cbf5621b1c656197/Task3/CheckIdentifier/CheckIdentifier/SemanticRule.cs#L18

**Comment by miredirex** [comment]
https://github.com/miredirex/backend-course/blob/16a0a8c1d7de0f1bc043bd5cbea41ede9d0e8281/Task3/CheckIdentifier/CheckIdentifier/SemanticRule.cs#L12-L16

Исправлено
Теперь возвращаю не true/false а объект, где также находится сообщение, почему не подходит под правило

**Comment by andrey-ilyin** [comment]
Принято.
