### ISSUE TITLE
По правилу SR3 идентификатор должен начинаться с буквы

### ISSUE THREAD

**Issue by andrey-ilyin** [miredirex/backend-course#2]
https://github.com/miredirex/backend-course/blob/c8fb5abcb1a73331dbef3007cbf5621b1c656197/Task3/CheckIdentifier/CheckIdentifier/SemanticRule.cs#L14

**Comment by miredirex** [comment]
https://github.com/miredirex/backend-course/blob/16a0a8c1d7de0f1bc043bd5cbea41ede9d0e8281/Task3/CheckIdentifier/CheckIdentifier/SemanticRule.cs#L34-L37

Исправлено

**Comment by andrey-ilyin** [comment]
Принято.
